import { createStore } from "framework7/lite";

const store = createStore({
  state: {
    city_sounds: [
      {
        id: 1,
        title: "Office",
        desc: "",
        cover: "../img/cs-office.jpg",
        sound: "../sound/cs-office.mp3",
      },
      {
        id: 2,
        title: "Shopping Mall",
        desc: "",
        cover: "../img/cs-mall.jpg",
        sound: "../sound/cs-mall.mp3",
      },
      {
        id: 3,
        title: "Cafe",
        desc: "",
        cover: "../img/cs-cafe.jpg",
        sound: "../sound/cs-cafe.mp3",
      },
      {
        id: 4,
        title: "Restaurant",
        desc: "",
        cover: "../img/cs-restaurant.jpg",
        sound: "../sound/cs-restaurant.mp3",
      },
      {
        id: 5,
        title: "Market",
        desc: "",
        cover: "../img/cs-market.jpg",
        sound: "../sound/cs-market.mp3",
      },
      {
        id: 6,
        title: "Central Park",
        desc: "",
        cover: "../img/cs-park.jpg",
        sound: "../sound/cs-park.mp3",
      },
      {
        id: 7,
        title: "Theme Park",
        desc: "",
        cover: "../img/cs-theme-park.jpg",
        sound: "../sound/cs-theme-park.mp3",
      },
      {
        id: 8,
        title: "Arcade Game Hall",
        desc: "",
        cover: "../img/cs-arcade-game.jpg",
        sound: "../sound/cs-arcade-game.mp3",
      },
      {
        id: 9,
        title: "NY Yankees Stadium",
        desc: "",
        cover: "../img/cs-ny-yankees-stadium.jpg",
        sound: "../sound/cs-yankee-stadium.mp3",
      },
      {
        id: 10,
        title: "Wembley Stadium",
        desc: "",
        cover: "../img/cs-wembley-stadium.jpg",
        sound: "../sound/cs-wembley-stadium.mp3",
      },
      {
        id: 11,
        title: "Airport Terminal",
        desc: "",
        cover: "../img/cs-airport-terminal.jpg",
        sound: "../sound/cs-airport-terminal.mp3",
      },
      {
        id: 12,
        title: "Subway",
        desc: "",
        cover: "../img/cs-subway.jpg",
        sound: "../sound/cs-subway.mp3",
      },
      {
        id: 13,
        title: "Train",
        desc: "",
        cover: "../img/cs-train.jpg",
        sound: "../sound/cs-train.mp3",
      },
      {
        id: 14,
        title: "Bus",
        desc: "",
        cover: "../img/cs-bus.jpg",
        sound: "../sound/cs-bus.mp3",
      },
      {
        id: 15,
        title: "Ferry",
        desc: "",
        cover: "../img/cs-ferry.jpg",
        sound: "../sound/cs-ferry.mp3",
      },
      {
        id: 16,
        title: "City Traffic",
        desc: "",
        cover: "../img/cs-city-traffic.jpg",
        sound: "../sound/cs-city-traffic.mp3",
      },
      {
        id: 17,
        title: "City Rain",
        desc: "",
        cover: "../img/cs-city-rain.jpg",
        sound: "../sound/cs-city-rain.mp3",
      },
      {
        id: 18,
        title: "Library",
        desc: "",
        cover: "../img/cs-library.jpg",
        sound: "../sound/cs-library.mp3",
      },
      {
        id: 24,
        title: "Museum Ambience",
        desc: "",
        cover: "../img/cs-museum.jpg",
        sound: "../sound/cs-museum.mp3",
      },
      {
        id: 19,
        title: "Public Restroom",
        desc: "",
        cover: "../img/cs-restroom.jpg",
        sound: "../sound/cs-restroom.mp3",
      },
      {
        id: 20,
        title: "Casino",
        desc: "",
        cover: "../img/cs-casino.jpg",
        sound: "../sound/cs-casino.mp3",
      },
      {
        id: 21,
        title: "Jazz Bar",
        desc: "",
        cover: "../img/cs-jazz-bar.jpg",
        sound: "../sound/cs-jazz-bar.mp3",
      },
      {
        id: 22,
        title: "Busy Bar",
        desc: "",
        cover: "../img/cs-busy-bar.jpg",
        sound: "../sound/cs-busy-bar.mp3",
      },
      {
        id: 23,
        title: "Nightclub",
        desc: "",
        cover: "../img/cs-nightclub.jpg",
        sound: "../sound/cs-nightclub.mp3",
      },
      // {
      //   id: 25,
      //   title: "Mosque Ambience",
      //   desc: "",
      //   cover: "../img/cs-mosque.jpg",
      //   sound: "",
      // },
      // {
      //   id: 26,
      //   title: "Church Ambience",
      //   desc: "",
      //   cover: "../img/cs-church.jpg",
      //   sound: "",
      // },
      // {
      //   id: 27,
      //   title: "Buddhist Temple",
      //   desc: "",
      //   cover: "../img/cs-buddhist-temple.jpg",
      //   sound: "",
      // },
      // {
      //   id: 28,
      //   title: "Hindu Temple",
      //   desc: "",
      //   cover: "../img/cs-hindu-temple.jpg",
      //   sound: "",
      // },
    ],
  },
  getters: {
    city_sounds({ state }) {
      return state.city_sounds;
    },
  },
  actions: {
    addCitySounds({ state }, city_sound) {
      state.city_sounds = [...state.city_sounds, city_sound];
    },
  },
});
export default store;
